namespace SFConfigManager.Main

exception ProjectNotFoundException
exception NoSolutionFoundException
exception MultipleSolutionsFoundException
exception SetArgumentsFailedException of errors: exn list